# Portail services for administration:

services:
    app.admin.structure:
        class: MNHN\PortailBundle\Admin\StructureAdmin
        arguments: [~, MNHN\PortailBundle\Entity\P_Structure, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Metier", label: "Structure" }
        public: true

    app.admin.skill:
        class: MNHN\PortailBundle\Admin\SkillAdmin
        arguments: [~, MNHN\PortailBundle\Entity\Skill, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Metier", label: "Skill" }
        public: true

    app.admin.program:
        class: MNHN\PortailBundle\Admin\ProgramAdmin
        arguments: [~, MNHN\PortailBundle\Entity\P_Program, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Metier", label: "Program" }
        #calls:
        #    - [ setTemplate, [edit, "@Builder/Field/fields_program_template.html.twig"]]
        public: true