# site_login: Pour surcharger login de fosuser
#     path:     /login
#     defaults: { _controller: MNHNAdminBundle:Builder\BuildPage:buildPage}

user_routing:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing.yml'
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

mnhn_admin:
    resource: "@MNHNAdminBundle/Resources/config/routing.yml"
    prefix:   /

mnhn_portail:
    resource: "@MNHNPortailBundle/Resources/config/routing.yml"
    prefix:   /

