services:
#    mnhn_portail.example:
#        class: MNHN\PortailBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    mnhn_portail.multiselectcreator:
        class: MNHN\PortailBundle\Utilities\MultiselectItemCreator

    mnhn_portail.js_vars:
        class: stdClass

    mnhn_portail.ecosystem.searchfilters:
        class: MNHN\PortailBundle\Services\ObservatoryList\SearchFilters
        arguments: [ "@doctrine.orm.entity_manager"]